import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
import pagefind from 'astro-pagefind';

export default defineConfig({
  site: 'https://plainsense.example.com',
  integrations: [mdx(), pagefind()],
  vite: {
    build: {
      rollupOptions: {
        // Pagefind is generated by the integration at build time and served at
        // /pagefind/pagefind.js. Mark it external so Rollup doesn't try to bundle it.
        external: ['/pagefind/pagefind.js'],
      },
    },
  },
});
